name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |

          if [ -z "$HF_TOKEN" ]; then
            echo "CRITICAL ERROR: Biến HF_TOKEN đang bị trống. Vui lòng kiểm tra lại GitHub Secrets."
            exit 1
          fi

          git config --global user.email "khang.buitranduycse@hcmut.edu.vn"
          git config --global user.name "Khang Bui Tran Duy"
          
          git push --force https://oauth2:$HF_TOKEN@huggingface.co/spaces/khangbkk23/epstein-rag-portfolio main